# https://mlflow.org

mlflow:
  _target_: pytorch_lightning.loggers.mlflow.MLFlowLogger
  experiment_name: default
  tracking_uri: http://192.168.1.24:49153
  tags: null
  save_dir: ./mlruns
  prefix: ""
  artifact_location: null
